#!/opt/news-aggregator/venv/bin/python3
"""Private, internal-only reading UI. Two views share one Flask app:

/ (breaking news) -- unchanged from Phase 1: renders clusters newest-first,
a cluster summary (multi-outlet) or a single item's own RSS description
(single-outlet), with outlet-level bias ratings shown when available.

/digest (Phase 2) -- twice-daily curated digest: only multi-outlet
clusters, each with an abridged multi-source summary and deviation notes
(what one outlet says that others don't), styled as a card with a hero
image when the source feed provided one, or a plain outlet-badge header
when it didn't (most feeds don't -- see the Phase 2 project doc).

/settings (Phase 2) -- a queue, not a write path: requests land in
source_requests and are never auto-added to feeds.json. Every feed added
to this project so far has needed live verification first (2 of the
original 9 candidate URLs were wrong; AP News turned out to have no
accessible feed at all) -- a submitted URL gets the same diligence, not a
shortcut around it.

The required non-authoritative caveat is always visible on the two
reading views."""

import json
from datetime import datetime, timedelta, timezone
from pathlib import Path
import sqlite3

from digest_text import coherent_event, dedupe_titles, repeat_story

from flask import Flask, redirect, render_template_string, request, url_for

FEEDS_PATH = Path(__file__).parent / "feeds.json"

DB_PATH = Path(__file__).parent / "news.db"
AUDIO_META_PATH = Path(__file__).parent / "static" / "digest-audio" / "latest.json"
app = Flask(__name__)


BC_OFFSET = timedelta(hours=-7)  # BC no longer observes DST; see the digest timer's own Etc/GMT+7


def get_audio_meta():
    try:
        meta = json.loads(AUDIO_META_PATH.read_text())
    except (FileNotFoundError, json.JSONDecodeError):
        return None
    generated_utc = datetime.fromisoformat(meta["generated_at"])
    local = generated_utc + BC_OFFSET
    meta["generated_local"] = local.strftime("%Y-%m-%d %H:%M")
    return meta

SITE_TITLE = "Your News"

HEAD_ICONS = """
<link rel="icon" type="image/png" sizes="32x32" href="/static/icon-32.png">
<link rel="apple-touch-icon" sizes="180x180" href="/static/icon-180.png">
<link rel="icon" type="image/png" sizes="512x512" href="/static/icon-512.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Your News">
<meta name="theme-color" content="#0b1020">
"""

NAV = """
<nav class="nav" aria-label="News navigation">
  <a class="{{ 'active' if active_page == 'breaking' else '' }}" href="/">Breaking news</a>
  <a class="{{ 'active' if active_page == 'digest' else '' }}" href="/digest">Digest</a>
  <a class="{{ 'active' if active_page == 'settings' else '' }}" href="/settings">Sources</a>
</nav>
"""

CAVEAT = """
<div class="caveat">
  Bias/slant labels are an automated, non-authoritative estimate &mdash;
  outlet ratings are manually cited from a named external source, and the
  highlighted phrase notes (if any) are generated by a local model and may
  be wrong. Neither is a factual claim about any outlet.
</div>
"""

SHARED_STYLE = """
  :root { color-scheme: dark; font-size: 16px; --ui-bg: #0b1020; --ui-panel: #151d31; --ui-panel-raised: #1b2740; --ui-panel-input: #111a2c; --ui-text: #f4f7fb; --ui-text-soft: #dce4f1; --ui-muted: #aab6ca; --ui-accent: #8bd3ff; --ui-accent-strong: #b9f2d0; --ui-danger: #ffaaa8; --ui-line: #2b3a58; }
  * { box-sizing: border-box; }
  body { margin: 0; background: radial-gradient(circle at top right, #25395a 0, var(--ui-bg) 48%); color: var(--ui-text); font: 16px/1.5 system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
  main { max-width: 1180px; margin: auto; padding: 42px 24px 72px; }
  .page-header { display: flex; justify-content: space-between; gap: 24px; align-items: end; margin-bottom: 28px; }
  .kicker, .eyebrow { color: var(--ui-accent); font-size: .78rem; font-weight: 750; letter-spacing: .12em; text-transform: uppercase; }
  .kicker { margin-bottom: 10px; }
  h1.brand { font-size: clamp(2.5rem, 7vw, 4.7rem); line-height: 1.02; margin: 0; letter-spacing: -.05em; }
  .page-intro { max-width: 570px; color: var(--ui-muted); margin: .85rem 0 0; }
  .header-stat { min-width: 160px; padding: 14px 16px; border: 1px solid var(--ui-line); border-radius: 14px; background: #111a2caa; color: var(--ui-muted); font-size: .78rem; }
  .header-stat strong { display: block; color: var(--ui-text); font-size: 1.35rem; line-height: 1.1; }
  .nav { display: flex; flex-wrap: wrap; gap: 10px; margin-bottom: 24px; }
  .nav a { display: inline-block; padding: 9px 15px; border: 1px solid var(--ui-line); border-radius: 999px; background: var(--ui-panel-input); color: var(--ui-muted); font-weight: 650; text-decoration: none; transition: background .15s, border-color .15s, color .15s; }
  .nav a:hover, .nav a.active { background: var(--ui-accent); border-color: var(--ui-accent); color: #07111d; }
  .caveat { color: var(--ui-muted); font-size: .8rem; margin: 0 0 24px; padding: 12px 14px; border: 1px solid var(--ui-line); border-radius: 12px; background: #111a2caa; }
  .toolbar { display: flex; align-items: center; gap: 12px; margin: 0 0 14px; }
  .toolbar label { color: var(--ui-muted); font-size: .8rem; white-space: nowrap; }
  .toolbar input, input[type=text], select, textarea { width: 100%; border: 1px solid var(--ui-line); border-radius: 10px; background: var(--ui-panel-input); color: var(--ui-text); font: inherit; padding: 10px 13px; }
  .toolbar input { width: min(520px, 100%); }
  .refreshed { margin-left: auto; color: var(--ui-muted); font-size: .76rem; white-space: nowrap; }
  a { color: var(--ui-accent); text-decoration: none; }
  a:hover { text-decoration: underline; }
  button { font: inherit; }
  :focus-visible { outline: 3px solid var(--ui-accent); outline-offset: 3px; }
  .rating { display: inline-block; background: #263450; color: var(--ui-accent); border-radius: 5px; padding: 1px 6px; font-size: .72rem; margin-left: 5px; cursor: help; border-bottom: 1px dotted #5c7bb0; }
  .no-rating { color: var(--ui-muted); font-size: .75rem; }
  footer { color: var(--ui-muted); font-size: .78rem; margin-top: 28px; }
  @media (max-width: 600px) { body { font-size: 17px; } main { padding: 28px 14px 56px; } .page-header { display: block; } .header-stat { margin-top: 20px; width: fit-content; padding: 16px 18px; } .nav a { padding: 11px 17px; } .toolbar { display: block; } .toolbar label { display: block; margin-bottom: 7px; } .toolbar input { padding: 13px 14px; } .refreshed { display: block; margin: 9px 0 0; } .caveat { padding: 14px 15px; } .cluster { padding: 20px; } .cluster h2 { font-size: 1.45rem; } .cluster-summary { font-size: 1rem; } }
"""

TEMPLATE = (
    """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ site_title }}</title>
"""
    + HEAD_ICONS
    + """
<style>
"""
    + SHARED_STYLE
    + """
  .cluster { background: linear-gradient(145deg, var(--ui-panel), #10182a); border: 1px solid var(--ui-line); border-radius: 18px; padding: 18px; margin-bottom: 18px; box-shadow: 0 12px 30px #0003; }
  .cluster[hidden] { display: none; }
  .cluster-head { display: flex; justify-content: space-between; gap: 16px; align-items: start; }
  .cluster h2 { font-size: 1.3rem; line-height: 1.15; margin: 5px 0 0; }
  .cluster-summary { color: var(--ui-text-soft); line-height: 1.55; margin: 14px 0; }
  .outlets { color: var(--ui-muted); font-size: .8rem; }
  .lang-note { color: #ffd36a; font-size: .82rem; margin-top: 12px; padding: 9px 11px; border-left: 3px solid #ffd36a; background: #2a241066; border-radius: 5px; }
  .section-label { color: var(--ui-muted); font-size: .8rem; margin: 0 0 12px; }
  .empty { padding: 50px; border: 1px dashed var(--ui-line); border-radius: 18px; color: var(--ui-muted); text-align: center; }
</style>
</head>
<body>
<main>
<header class="page-header"><div><div class="kicker">Private news desk</div><h1 class="brand">{{ site_title }}</h1><p class="page-intro">Scan the latest coverage, compare how outlets frame the same event, and follow the stories worth your attention.</p></div><div class="header-stat"><strong>{{ clusters|length }}</strong> story clusters in view</div></header>
"""
    + NAV
    + CAVEAT
    + """
<div class="toolbar"><label for="story-search">Find in coverage</label><input id="story-search" type="search" placeholder="Search headlines, summaries or outlets…" autocomplete="off"><span class="refreshed">Updated from the latest feed run</span></div>
<p class="section-label">Breaking coverage · multi-outlet stories are grouped together</p>
<section id="story-list" aria-live="polite">
{% for c in clusters %}
<article class="cluster" data-search="{{ (c.headline ~ ' ' ~ (c.summary or c.raw_summary) ~ ' ' ~ (c.outlets | map(attribute='feed_id') | join(' '))) | lower | e }}">
  <div class="cluster-head"><div><div class="eyebrow">Story cluster</div><h2>{{ c.headline }}</h2></div><span class="header-stat"><strong>{{ c.outlets|length }}</strong> sources</span></div>
  {% if c.summary %}<p class="cluster-summary">{{ c.summary }}</p>{% else %}<p class="cluster-summary">{{ c.raw_summary }}</p>{% endif %}
  <div class="outlets">
    {% for o in c.outlets %}
      <a href="{{ o.link }}" target="_blank">{{ o.feed_id }}</a>{% if o.rating %}<span class="rating" title="{{ o.rating_source }}{% if o.rating_notes %} &mdash; {{ o.rating_notes }}{% endif %}">{{ o.rating }}</span>{% else %}<span class="no-rating"> (no rating)</span>{% endif %}{% if not loop.last %} &middot; {% endif %}
    {% endfor %}
  </div>
  {% if c.lang_note %}<div class="lang-note">Note: {{ c.lang_note }}</div>{% endif %}
</article>
{% endfor %}
</section>
<div id="story-empty" class="empty" hidden><h2>No matching coverage</h2><p>Try a different headline, summary phrase or outlet.</p></div>
<footer>Coverage is grouped and summarized locally. Outlet labels and model notes are non-authoritative; open the source links for the original reporting.</footer>
</main>
<script>
const storySearch = document.querySelector('#story-search');
const storyCards = document.querySelectorAll('.cluster');
const storyEmpty = document.querySelector('#story-empty');
storySearch.addEventListener('input', () => {
  const query = storySearch.value.trim().toLowerCase(); let visible = 0;
  storyCards.forEach((card) => { const match = !query || card.dataset.search.includes(query); card.hidden = !match; if (match) visible += 1; });
  storyEmpty.hidden = visible !== 0;
});
</script>
</body>
</html>
"""
)

TEMPLATE_DIGEST = (
    """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ site_title }} - Digest</title>
"""
    + HEAD_ICONS
    + """
<style>
"""
    + SHARED_STYLE
    + """
  .digest-card { background: linear-gradient(145deg, var(--ui-panel), #10182a); border: 1px solid var(--ui-line); border-radius: 18px; overflow: hidden; margin-bottom: 18px; box-shadow: 0 12px 30px #0003; }
  .digest-card[hidden] { display: none; }
  .digest-hero { width: 100%; max-height: 360px; object-fit: cover; display: block; background: var(--ui-panel-raised); }
  .digest-badge-header { padding: 16px 18px 0; }
  .digest-source { color: var(--ui-muted); font-size: .76rem; font-weight: 650; letter-spacing: .08em; text-transform: uppercase; }
  .digest-source.on-image { padding: 12px 18px 0; }
  .digest-body { padding: 16px 18px 18px; }
  .digest-headline { font-size: 1.45rem; font-weight: 750; margin: .35rem 0 .65rem; line-height: 1.15; letter-spacing: -.02em; }
  .digest-summary { color: var(--ui-text-soft); line-height: 1.55; margin: 0; }
  .digest-deviation { margin-top: 14px; padding: 11px 13px; background: #2a241066; border-left: 3px solid #ffd36a; font-size: .86rem; color: #ffd36a; border-radius: 5px; }
  .digest-deviation strong { display: block; color: #fff0b5; font-size: .72rem; letter-spacing: .1em; text-transform: uppercase; margin-bottom: 3px; }
  .digest-outlets { margin-top: 14px; font-size: .8rem; color: var(--ui-muted); }
  .digest-image-credit { padding: 7px 18px 0; color: var(--ui-muted); font-size: .72rem; line-height: 1.3; }
  .digest-image-credit a { color: inherit; }
  .empty { color: var(--ui-muted); padding: 50px; border: 1px dashed var(--ui-line); border-radius: 18px; text-align: center; }
  .audio-briefing { background: linear-gradient(135deg, #172842, #151d31); border: 1px solid var(--ui-line); border-radius: 18px; padding: 18px; margin-bottom: 24px; }
  .audio-briefing-label { color: var(--ui-accent-strong); font-size: .78rem; font-weight: 700; letter-spacing: .1em; text-transform: uppercase; margin-bottom: 12px; }
  .audio-player { display: block; }
  .audio-main { min-width: 0; }
  .audio-briefing audio { display: block; width: 100%; height: 54px; }
  .audio-controls { display: flex; flex-wrap: wrap; gap: 8px; margin-top: 9px; }
  .audio-control { margin: 0; padding: 7px 10px; border: 1px solid var(--ui-line); border-radius: 9px; background: var(--ui-panel-input); color: var(--ui-text-soft); cursor: pointer; font-size: .8rem; }
  .audio-control:hover, .audio-control:focus-visible { border-color: var(--ui-accent); color: var(--ui-accent); }
  .audio-chapters-stage { --audio-level: .2; position: relative; min-height: 220px; overflow: hidden; margin-top: 14px; border: 1px solid var(--ui-line); border-radius: 14px; background: #0b1020aa; isolation: isolate; }
  .audio-chapters-stage::after { content: ""; position: absolute; inset: 0; z-index: 0; pointer-events: none; background: linear-gradient(90deg, #0b1020cc 0%, #0b102066 48%, #0b1020cc 100%); }
  .audio-orb { position: absolute; z-index: 0; top: 50%; left: 50%; width: 320px; height: 320px; border-radius: 50%; object-fit: cover; opacity: .16; filter: saturate(.35) brightness(calc(.85 + (var(--audio-level) * .35))); pointer-events: none; transform: translate(-50%, -50%) scale(calc(1 + (var(--audio-level) * .16))); transform-origin: center; box-shadow: 0 0 calc(16px + (var(--audio-level) * 36px)) color-mix(in srgb, var(--ui-accent) 35%, transparent); transition: transform .08s linear, filter .08s linear, box-shadow .08s linear; }
  .audio-chapters { position: relative; z-index: 1; display: grid; gap: 5px; margin: 0; padding: 14px; list-style: none; }
  .audio-chapter { display: flex; align-items: baseline; gap: 8px; width: 100%; padding: 7px 9px; border: 1px solid transparent; border-radius: 8px; background: #111a2caa; color: var(--ui-muted); text-align: left; cursor: pointer; font: inherit; font-size: .82rem; backdrop-filter: blur(2px); }
  .audio-chapter:hover, .audio-chapter[aria-current="true"] { background: #263450; border-color: var(--ui-line); color: var(--ui-text); }
  .audio-chapter-time { color: var(--ui-accent); font-variant-numeric: tabular-nums; min-width: 3.3em; }
  @media (prefers-reduced-motion: reduce) { .audio-orb { transition: none; } }
  .digest-toolbar { margin-bottom: 24px; }
  .filters { display: flex; flex-wrap: wrap; gap: 10px; padding: 14px; background: var(--ui-panel-input); border: 1px solid var(--ui-line); border-radius: 16px; margin-bottom: 24px; }
  .filter { border: 1px solid var(--ui-line); background: transparent; color: var(--ui-muted); border-radius: 999px; padding: 9px 15px; cursor: pointer; }
  .filter.active, .filter:hover { background: var(--ui-accent); color: #07111d; border-color: var(--ui-accent); }
  .filter span { font-size: .8em; opacity: .75; }
  @media (max-width: 600px) { .audio-briefing { padding: 20px; } .audio-briefing audio { height: 60px; } .audio-chapters-stage { min-height: 260px; } .audio-orb { width: 320px; height: 320px; } .digest-body { padding: 20px; } .digest-headline { font-size: 1.55rem; } .digest-summary { font-size: 1rem; } .digest-deviation { font-size: .95rem; padding: 13px 14px; } .filter { padding: 11px 16px; } }
</style>
</head>
<body>
<main>
<header class="page-header"><div><div class="kicker">Twice-daily local briefing</div><h1 class="brand">{{ site_title }}</h1><p class="page-intro">The stories that made the wider news cycle, condensed with multiple outlets in view and the important differences called out.</p></div><div class="header-stat"><strong>{{ entries|length }}</strong> stories in this briefing</div></header>
"""
    + NAV
    + CAVEAT
    + """
{% if audio %}
<div class="audio-briefing">
  <div class="audio-briefing-label">Listen to the briefing &middot; {{ audio.story_count }} {{ "story" if audio.story_count == 1 else "stories" }} &middot; generated {{ audio.generated_local }}</div>
  <div class="audio-player">
    <div class="audio-main">
      <audio id="briefing-audio" controls preload="none" src="/static/digest-audio/latest.mp3">
        <track kind="chapters" srclang="en" label="Stories" src="/static/digest-audio/latest.vtt" default>
      </audio>
      <div class="audio-controls" aria-label="Audio controls">
        <button type="button" class="audio-control" data-seek="-20">&minus;20s</button>
        <button type="button" class="audio-control" id="previous-chapter">Previous story</button>
        <button type="button" class="audio-control" id="next-chapter">Next story</button>
        <button type="button" class="audio-control" data-seek="10">+10s</button>
      </div>
    </div>
  </div>
  {% if audio.chapters %}
  <div class="audio-chapters-stage" id="audio-chapters-stage">
    <img id="audio-orb" class="audio-orb" src="/static/aster-orb.png" alt="">
    <ol class="audio-chapters" id="audio-chapters" aria-label="Briefing chapters">
      {% for chapter in audio.chapters %}<li><button type="button" class="audio-chapter" data-start="{{ chapter.start }}"><span class="audio-chapter-time">{{ "%02d:%02d"|format((chapter.start // 60)|int, (chapter.start % 60)|int) }}</span><span>{{ chapter.title }}</span></button></li>{% endfor %}
    </ol>
  </div>
  {% endif %}
</div>
{% endif %}
<div class="toolbar digest-toolbar"><label for="briefing-search">Find in briefing</label><input id="briefing-search" type="search" placeholder="Search headlines, summaries or outlets…" autocomplete="off"><span class="refreshed">{{ briefing_updated }}</span></div>
<nav class="filters" aria-label="Filter briefing by source"><button type="button" class="filter active" data-filter="all">All <span>{{ entries|length }}</span></button>{% for source, count in briefing_sources %}<button type="button" class="filter" data-filter="{{ source|e }}">{{ source }} <span>{{ count }}</span></button>{% endfor %}</nav>
{% if not entries %}<div class="empty"><h2>No briefing yet</h2><p>The next scheduled run will generate one for every notable, multi-outlet story.</p></div>{% endif %}
<section id="briefing-list" aria-live="polite">
{% for e in entries %}
<article class="digest-card" data-sources="{{ e.outlets | map(attribute='feed_id') | join('|') | e }}" data-search="{{ (e.headline ~ ' ' ~ e.summary ~ ' ' ~ (e.outlets | map(attribute='feed_id') | join(' '))) | lower | e }}">
  {% if e.image_url %}
  <img class="digest-hero" src="{{ e.image_url }}" alt="News image for {{ e.headline }}" loading="lazy">
  <div class="digest-source on-image">{{ e.outlets | map(attribute='feed_id') | join(' &middot; ') | safe }}</div>
  {% if e.image_credit %}<div class="digest-image-credit">{% if e.image_source_url %}<a href="{{ e.image_source_url }}" target="_blank" rel="noreferrer">{{ e.image_credit }}</a>{% else %}{{ e.image_credit }}{% endif %}</div>{% endif %}
  {% else %}
  <div class="digest-badge-header">
    <div class="digest-source">{{ e.outlets | map(attribute='feed_id') | join(' &middot; ') | safe }}</div>
  </div>
  {% endif %}
  <div class="digest-body">
    <div class="digest-headline">{{ e.headline }}</div>
    <p class="digest-summary">{{ e.summary }}</p>
    {% if e.deviation_notes %}<div class="digest-deviation"><strong>What differs between sources</strong>{{ e.deviation_notes }}</div>{% endif %}
    <div class="digest-outlets">
      {% for o in e.outlets %}
        <a href="{{ o.link }}" target="_blank">{{ o.feed_id }}</a>{% if o.rating %}<span class="rating" title="{{ o.rating_source }}{% if o.rating_notes %} &mdash; {{ o.rating_notes }}{% endif %}">{{ o.rating }}</span>{% else %}<span class="no-rating"> (no rating)</span>{% endif %}{% if not loop.last %} &middot; {% endif %}
      {% endfor %}
    </div>
  </div>
</article>
{% endfor %}
</section>
<div id="briefing-empty" class="empty" hidden><h2>No matching stories</h2><p>Try a different headline, summary phrase or outlet.</p></div>
<footer>Stories are selected from multiple outlets and summarized locally. Source links open the original reporting; model-generated summaries and deviation notes may be wrong.</footer>
</main>
<script>
const briefingSearch = document.querySelector('#briefing-search');
const briefingCards = document.querySelectorAll('.digest-card');
const briefingEmpty = document.querySelector('#briefing-empty');
const briefingFilters = document.querySelectorAll('.filter');
let briefingFilter = 'all';
function applyBriefingFilters() {
  const query = briefingSearch.value.trim().toLowerCase(); let visible = 0;
  briefingCards.forEach((card) => { const matchesSource = briefingFilter === 'all' || card.dataset.sources.split('|').includes(briefingFilter); const matchesSearch = !query || card.dataset.search.includes(query); const match = matchesSource && matchesSearch; card.hidden = !match; if (match) visible += 1; });
  briefingEmpty.hidden = visible !== 0;
}
briefingSearch.addEventListener('input', () => {
  applyBriefingFilters();
});
briefingFilters.forEach((filter) => filter.addEventListener('click', () => { briefingFilters.forEach((item) => item.classList.remove('active')); filter.classList.add('active'); briefingFilter = filter.dataset.filter; applyBriefingFilters(); }));

const briefingAudio = document.querySelector('#briefing-audio');
const audioStage = document.querySelector('#audio-chapters-stage');
const audioOrb = document.querySelector('#audio-orb');
const chapterButtons = [...document.querySelectorAll('.audio-chapter')];
const chapterStarts = chapterButtons.map((button) => Number(button.dataset.start));
let audioContext; let analyser; let audioSource; let audioFrame;

function currentChapter() {
  let index = -1;
  chapterStarts.forEach((start, candidate) => { if (briefingAudio.currentTime >= start - .4) index = candidate; });
  return index;
}
function updateChapterState() {
  const current = currentChapter();
  chapterButtons.forEach((button, index) => button.setAttribute('aria-current', index === current ? 'true' : 'false'));
}
function animateAudio() {
  if (!analyser || briefingAudio.paused) return;
  const data = new Uint8Array(analyser.frequencyBinCount); analyser.getByteFrequencyData(data);
  const average = data.reduce((sum, value) => sum + value, 0) / Math.max(1, data.length);
  const level = Math.min(1, average / 105); audioStage?.style.setProperty('--audio-level', level.toFixed(3)); audioOrb?.style.setProperty('--audio-level', level.toFixed(3));
  audioFrame = requestAnimationFrame(animateAudio);
}
function stopAudioAnimation() { if (audioFrame) cancelAnimationFrame(audioFrame); audioFrame = null; audioStage?.classList.remove('playing'); audioStage?.style.setProperty('--audio-level', '.2'); audioOrb?.style.setProperty('--audio-level', '.2'); }
function startAudioAnimation() {
  if (!audioContext) { audioContext = new AudioContext(); analyser = audioContext.createAnalyser(); analyser.fftSize = 64; audioSource = audioContext.createMediaElementSource(briefingAudio); audioSource.connect(analyser); analyser.connect(audioContext.destination); }
  if (audioContext.state === 'suspended') audioContext.resume();
  audioStage?.classList.add('playing'); animateAudio();
}
chapterButtons.forEach((button) => button.addEventListener('click', () => { briefingAudio.currentTime = Number(button.dataset.start); briefingAudio.play(); }));
document.querySelectorAll('[data-seek]').forEach((button) => button.addEventListener('click', () => { briefingAudio.currentTime = Math.max(0, briefingAudio.currentTime + Number(button.dataset.seek)); }));
document.querySelector('#previous-chapter')?.addEventListener('click', () => { const current = currentChapter(); const target = current > 0 && briefingAudio.currentTime - chapterStarts[current] > 3 ? chapterStarts[current] : chapterStarts[Math.max(0, current - 1)]; if (target !== undefined) briefingAudio.currentTime = target; });
document.querySelector('#next-chapter')?.addEventListener('click', () => { const next = chapterStarts.find((start) => start > briefingAudio.currentTime + .8); if (next !== undefined) briefingAudio.currentTime = next; });
briefingAudio?.addEventListener('timeupdate', updateChapterState);
briefingAudio?.addEventListener('play', startAudioAnimation);
briefingAudio?.addEventListener('pause', stopAudioAnimation);
briefingAudio?.addEventListener('ended', stopAudioAnimation);
</script>
</body>
</html>
"""
)

TEMPLATE_SETTINGS = (
    """
<!doctype html>
<html>
<head>
<meta charset="utf-8">
<title>{{ site_title }} - Settings</title>
"""
    + HEAD_ICONS
    + """
<style>
"""
    + SHARED_STYLE
    + """
  fieldset { border: 1px solid var(--ui-line); border-radius: 18px; padding: 18px; margin: 0 0 24px; background: linear-gradient(145deg, var(--ui-panel), #10182a); }
  legend { font-weight: 700; padding: 0 8px; color: var(--ui-text); }
  label { display: block; margin-top: 14px; font-size: .86rem; font-weight: 700; color: var(--ui-text-soft); }
  label .hint { font-weight: 400; color: var(--ui-muted); }
  input[type=text], select, textarea { margin-top: 5px; }
  textarea { min-height: 6rem; resize: vertical; }
  button { margin-top: 16px; padding: 10px 15px; background: var(--ui-accent); color: #07111d; border: 0; border-radius: 10px; font-weight: 750; cursor: pointer; }
  button:hover { filter: brightness(1.08); }
  .queue-note { font-size: .86rem; color: var(--ui-muted); margin-bottom: 18px; }
  table { width: 100%; border-collapse: collapse; background: var(--ui-panel); border: 1px solid var(--ui-line); border-radius: 12px; overflow: hidden; }
  th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid var(--ui-line); font-size: .82rem; }
  th { background: var(--ui-panel-raised); color: var(--ui-text-soft); }
  .status-pending { color: #ffd36a; }
  .flash { background: #16301f; border: 1px solid #2a5a3a; color: var(--ui-accent-strong); border-radius: 10px; padding: 10px 14px; margin-bottom: 18px; font-size: .9rem; }
  .settings-heading { margin: 0 0 8px; }
</style>
</head>
<body>
<main>
<header class="page-header"><div><div class="kicker">Private source desk</div><h1 class="brand">{{ site_title }}</h1><p class="page-intro">Request new sources for review. The live feed list remains unchanged until a source is verified and approved.</p></div></header>
"""
    + NAV
    + """
{% if flash %}<div class="flash">{{ flash }}</div>{% endif %}
<div class="queue-note">
  Requests are queued for manual verification before being added -- every
  feed in this project so far has needed a real, live check first (some
  candidate URLs turned out wrong; one source had no accessible feed at
  all). Submitting here never edits the live feed list directly.
</div>
<form method="post">
  <fieldset>
    <legend>Request new sources</legend>
    <label>Category
      <span class="hint">pick an existing one, or choose "New category" and name it below</span>
    </label>
    <select name="category_choice">
      {% for c in categories %}<option value="{{ c }}">{{ c }}</option>{% endfor %}
      <option value="__new__">New category&hellip;</option>
    </select>
    <label>New category name <span class="hint">(only used if "New category" is selected above)</span></label>
    <input type="text" name="new_category" placeholder="e.g. photography">
    <label>Sources <span class="hint">one per line, as: Name | URL</span></label>
    <textarea name="sources" placeholder="PetaPixel | https://petapixel.com/feed/&#10;DPReview | https://www.dpreview.com/feeds/news.xml" required></textarea>
    <label>Note <span class="hint">(optional)</span></label>
    <input type="text" name="note" placeholder="Why you want this source/section">
    <button type="submit">Submit request</button>
  </fieldset>
</form>
<h2 class="settings-heading">Pending requests</h2>
{% if not requests %}
<p class="queue-note">Nothing queued right now.</p>
{% else %}
<table>
  <tr><th>Requested</th><th>Category</th><th>Name</th><th>URL</th><th>Status</th></tr>
  {% for r in requests %}
  <tr>
    <td>{{ r.requested_at[:10] }}</td>
    <td>{{ r.category }}{% if r.is_new_category %} <em>(new)</em>{% endif %}</td>
    <td>{{ r.requested_name }}</td>
    <td>{% if r.requested_url %}<a href="{{ r.requested_url }}" target="_blank">{{ r.requested_url }}</a>{% endif %}</td>
    <td class="status-{{ r.status }}">{{ r.status }}</td>
  </tr>
  {% endfor %}
</table>
{% endif %}
</main>
</body>
</html>
"""
)


def _outlets_for_cluster(conn: sqlite3.Connection, cluster_id: int, items: list[sqlite3.Row]) -> list[dict]:
    outlets = []
    seen_feed_ids = set()
    for item in items:
        # A cluster can contain more than one item from the same feed_id
        # (e.g. a source cross-posting one story under several URLs, now
        # merged by cluster.py's same-outlet matching) -- show that
        # outlet's badge once, not once per duplicate row.
        if item["feed_id"] in seen_feed_ids:
            continue
        seen_feed_ids.add(item["feed_id"])
        rating = conn.execute(
            "SELECT rating_label, source_name, notes FROM outlet_ratings WHERE feed_id = ?",
            (item["feed_id"],),
        ).fetchone()
        outlets.append({
            "feed_id": item["feed_id"],
            "link": item["link"],
            "rating": rating["rating_label"] if rating else None,
            "rating_source": rating["source_name"] if rating else None,
            "rating_notes": rating["notes"] if rating else None,
        })
    return outlets


def get_clusters(limit: int = 40):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    cluster_ids = [
        row["cluster_id"]
        for row in conn.execute(
            "SELECT cluster_id, MAX(fetched_at) AS latest FROM feed_items "
            "WHERE cluster_id IS NOT NULL GROUP BY cluster_id "
            "ORDER BY latest DESC LIMIT ?",
            (limit,),
        )
    ]
    clusters = []
    for cid in cluster_ids:
        items = conn.execute(
            "SELECT id, feed_id, title, link, summary FROM feed_items WHERE cluster_id = ?",
            (cid,),
        ).fetchall()
        if not items:
            continue
        summary_row = conn.execute(
            "SELECT summary FROM cluster_summaries WHERE cluster_id = ?", (cid,)
        ).fetchone()
        outlets = _outlets_for_cluster(conn, cid, items)
        lang_note = None
        for item in items:
            note_row = conn.execute(
                "SELECT note FROM item_language_notes WHERE item_id = ? AND note IS NOT NULL",
                (item["id"],),
            ).fetchone()
            if note_row and not lang_note:
                lang_note = note_row["note"]
        clusters.append({
            "headline": items[0]["title"],
            "summary": summary_row["summary"] if summary_row else None,
            "raw_summary": items[0]["summary"],
            "outlets": outlets,
            "lang_note": lang_note,
        })
    conn.close()
    return clusters


def get_digest_entries(limit: int = 21):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    latest_run = conn.execute("SELECT MAX(digest_run) AS run FROM digest_entries").fetchone()["run"]
    previous_run = conn.execute(
        "SELECT MAX(digest_run) AS run FROM digest_entries WHERE digest_run < ?",
        (latest_run,),
    ).fetchone()["run"] if latest_run else None
    digest_columns = {row[1] for row in conn.execute("PRAGMA table_info(digest_entries)")}
    optional_image_columns = ", image_credit, image_source_url" if {"image_credit", "image_source_url"}.issubset(digest_columns) else ""
    rows = conn.execute(
        "SELECT cluster_id, abridged_summary, deviation_notes, image_url" + optional_image_columns + " "
        "FROM digest_entries WHERE digest_run = ? ORDER BY generated_at DESC LIMIT ?",
        (latest_run, limit * 2),
    ).fetchall()
    previous_titles = []
    if previous_run:
        previous_titles = [
            row["title"] for row in conn.execute(
                "SELECT fi.title FROM feed_items fi "
                "JOIN (SELECT DISTINCT cluster_id FROM digest_entries WHERE digest_run = ?) old "
                "ON old.cluster_id = fi.cluster_id",
                (previous_run,),
            ).fetchall()
        ]
    entries = []
    for de in rows:
        cid = de["cluster_id"]
        items = conn.execute(
            "SELECT id, feed_id, title, link FROM feed_items WHERE cluster_id = ?",
            (cid,),
        ).fetchall()
        items = coherent_event(items)
        if not items:
            continue
        if len({item["feed_id"] for item in items}) < 2:
            continue
        entries.append({
            "title": items[0]["title"],
            "headline": items[0]["title"],
            "summary": de["abridged_summary"],
            "dedupe_text": de["abridged_summary"],
            "deviation_notes": de["deviation_notes"],
            "image_url": de["image_url"],
            "image_credit": de["image_credit"] if "image_credit" in de.keys() else None,
            "image_source_url": de["image_source_url"] if "image_source_url" in de.keys() else None,
            "outlets": _outlets_for_cluster(conn, cid, items),
        })
    entries = [
        entry for entry in entries
        if not any(repeat_story(entry["headline"], old_title) for old_title in previous_titles)
    ]
    entries = dedupe_titles(entries, text_key="dedupe_text")[:limit]
    conn.close()
    return entries


def get_digest_updated_at() -> str:
    """Return the latest digest generation time in the established BC local time."""
    conn = sqlite3.connect(DB_PATH)
    row = conn.execute("SELECT MAX(generated_at) AS generated FROM digest_entries").fetchone()
    conn.close()
    if not row or not row[0]:
        return "Waiting for the first digest run"
    try:
        generated = datetime.fromisoformat(row[0].replace("Z", "+00:00")) + BC_OFFSET
        return f"Updated {generated.strftime('%b %-d, %Y at %-I:%M %p')}"
    except ValueError:
        return "Updated from the latest digest run"


def get_known_categories() -> list[str]:
    feeds = json.loads(FEEDS_PATH.read_text())["feeds"]
    seen = []
    for feed in feeds:
        cat = feed.get("category")
        if cat and cat not in seen:
            seen.append(cat)
    return seen


def get_pending_requests(limit: int = 100):
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute(
        "SELECT requested_name, requested_url, category, is_new_category, note, status, requested_at "
        "FROM source_requests ORDER BY requested_at DESC LIMIT ?",
        (limit,),
    ).fetchall()
    conn.close()
    return rows


def _parse_source_line(line: str) -> tuple[str, str | None]:
    """"Name | URL" if both given, or just a bare name/URL on its own."""
    if "|" in line:
        name, _, url = line.partition("|")
        return name.strip(), url.strip() or None
    return line.strip(), None


@app.context_processor
def inject_site_title():
    return {"site_title": SITE_TITLE, "active_page": ""}


@app.route("/")
def index():
    return render_template_string(TEMPLATE, clusters=get_clusters(), active_page="breaking")


@app.route("/digest")
def digest():
    entries = get_digest_entries()
    source_counts = {}
    for entry in entries:
        for outlet in entry["outlets"]:
            source_counts[outlet["feed_id"]] = source_counts.get(outlet["feed_id"], 0) + 1
    return render_template_string(TEMPLATE_DIGEST, entries=entries, audio=get_audio_meta(),
                                  briefing_updated=get_digest_updated_at(),
                                  briefing_sources=sorted(source_counts.items()), active_page="digest")


@app.route("/settings", methods=["GET", "POST"])
def settings():
    flash = None
    if request.method == "POST":
        category_choice = (request.form.get("category_choice") or "").strip()
        is_new = category_choice == "__new__"
        category = (request.form.get("new_category") or "").strip() if is_new else category_choice
        note = (request.form.get("note") or "").strip() or None
        lines = [ln.strip() for ln in (request.form.get("sources") or "").splitlines() if ln.strip()]

        if not category:
            flash = "No category given -- request not saved. Pick an existing one or name a new one."
        elif not lines:
            flash = "No sources given -- request not saved."
        else:
            conn = sqlite3.connect(DB_PATH)
            now = datetime.now(timezone.utc).isoformat()
            for line in lines:
                name, url = _parse_source_line(line)
                if not name:
                    continue
                conn.execute(
                    "INSERT INTO source_requests "
                    "(requested_name, requested_url, category, is_new_category, note, status, requested_at) "
                    "VALUES (?, ?, ?, ?, ?, 'pending', ?)",
                    (name, url, category, int(is_new), note, now),
                )
            conn.commit()
            conn.close()
            # Redirect (POST/redirect/GET) so refreshing the settings page
            # never resubmits the form.
            return redirect(url_for("settings", saved=len(lines)))

    if request.args.get("saved"):
        flash = f"{request.args['saved']} source request(s) queued for review."

    return render_template_string(
        TEMPLATE_SETTINGS,
        categories=get_known_categories(),
        requests=get_pending_requests(),
        flash=flash,
        active_page="settings",
    )


@app.route("/healthz")
def healthz():
    try:
        conn = sqlite3.connect(DB_PATH)
        conn.execute("SELECT 1 FROM feed_items LIMIT 1")
        conn.close()
        return {"status": "ok"}, 200
    except Exception as exc:  # noqa: BLE001
        return {"status": "error", "detail": str(exc)}, 503


if __name__ == "__main__":
    app.run(host="192.168.70.13", port=8080)
