#!/usr/sbin/nft -f

flush ruleset

table inet aster_wiki {
    chain input {
        type filter hook input priority filter; policy accept;

        iifname "lo" accept
        ip saddr 192.168.50.23 tcp dport 8787 accept
        tcp dport 8787 drop
    }

    chain forward {
        type filter hook forward priority filter; policy accept;
    }

    chain output {
        type filter hook output priority filter; policy accept;
    }
}
